name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.0

      - name: Setup Cog
        uses: replicate/setup-cog@v1.0.2
        with:
          token: ${r8_TCq8HrBWbijrTMOigxInaOAcsZJUtxL3HJPsA}

      - name: Push to Replicate
        run: |
          cog push r8.im/ikun-ai/sdxl-inpanting
