name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.0
        
      - name: Log in to Replicate
        shell: bash
        if: ${{ inputs.token != '' }}
        env:
          REPLICATE_API_TOKEN: ${{ inputs.token }}
        run: |
          echo "Found REPLICATE_API_TOKEN in the environment; Authenticating..."
          echo $REPLICATE_API_TOKEN | cog login --token-stdin
        
      - name: Download weights
        run: cog run script/download-weights

      - name: Push to Replicate
        run: |
          cog push r8.im/ikun-ai/sdxl-inpanting
